### ISSUE TITLE
Please make one for XMRig Proxy Web API

### ISSUE THREAD

**Issue by dorimanx** [dunklesToast/XMRigFrontend#1]
Hi,

Will be really great to have xmrig proxy web interface.

Currently we have json page with stats, and it's already nice.

But if that can be made with colors and some real web page, it's can be just awesome!

I can provide live proxy feed web api, so you can test on it. if you like.

Thanks!

**Comment by dunklesToast** [comment]
That's a good idea. Would be really nice if you could provide me the live feed since I just use the CPU Version!

**Comment by dorimanx** [comment]
can i send it by mail? not really like to publish it for whole world to see!

**Comment by dunklesToast** [comment]
Sure! You can use dunklestoast@gmail.com for that!

**Comment by dorimanx** [comment]
Sent you the proxy IP and port. it's just API, not much to do with it :)
Hope to see cool interface, i am sure @xmrig will be happy too!

**Comment by dunklesToast** [comment]
I received it and started implementing it. I think in the new Release you can add as many xmrig's as you want and maybe sync the data between computers - I hope its done in two weeks. I am a bit busy currently

**Comment by dorimanx** [comment]
Well you made great interface! deep respect for your hard work!
