### ISSUE TITLE
Doesn't work with xmrig-proxy 2.5

### ISSUE THREAD

**Issue by kimats** [dunklesToast/XMRigFrontend#10]
With Xmrig-proxy 2.5，the software doesn't get any data, could you please have a look?
I can use other software to get info form API. But I think your software is better.

**Comment by dunklesToast** [comment]
Hey! I‘ll take a Look! Could you please provide some more information? Do you use Bearer Auth? What IP Address do you enter on the page?

**Comment by kimats** [comment]
Hmmm, i put it on LAN server, is it due to the change ?
https://github.com/xmrig/xmrig-proxy/releases :
"Deprecations:
API endpoint GET /workers.json, use GET /1/workers instead."

**Comment by dunklesToast** [comment]
Hi!

Yea. I think that’s the problem. Haven’t heard about the API Change. I did change the workers route in the code - Would be nice if you could test it, since I do not use the proxy!

**Comment by dunklesToast** [comment]
Just saw that also the / route changed. I will fix that this evening

**Comment by kimats** [comment]
@dunklesToast 
Thanks man! I will test when you fix the proxy part!

**Comment by dunklesToast** [comment]
So. If I didn't made any mistakes, it should work with the newest version of the proxy

**Comment by kimats** [comment]
looks like doest work for me,
RIG URL is the  ip address of rig?
RIG PORT is the PORT defined in miner'S API?
i dont set the token so leave it blank.

**Comment by kimats** [comment]
OK, My mistake, use http://ip address works fine. 
very amazing program.
Thank you.
