### ISSUE TITLE
Website in info

### ISSUE THREAD

**Issue by samyok** [dunklesToast/XMRigFrontend#11]
The website in the info for the repo is wrong and no longer works. 

It should be https://dunklestoast.github.io/XMRigFrontend/index.html

**Comment by dunklesToast** [comment]
Which one did you mean?
I linked two pages. One is the github.io Website and the other one is [this one](http://xmrig.dunklestoast.de/). The last one was broken, I fixed it now.
The reason why there are both is, that the GitHub.io page just allows HTTPS and most Miners do not have HTTPS so you would get a "Mixed Content" error (#2). [This one](http://xmrig.dunklestoast.de/) has SSL disabled so you can use it for any miner without getting errors!

**Comment by samyok** [comment]
Nevermind--someone must have fixed it.

**Comment by dunklesToast** [comment]
Yea. I fixed after you noticed the error! Made a mistake in my NGINX Config...
