### ISSUE TITLE
Help with integration with miner

### ISSUE THREAD

**Issue by diegosantos92** [dunklesToast/XMRigFrontend#3]
Hello, first of all, I want to thank you for the initiative and for making this project available. FrontEnd has all the capabilities to monitor my miners and proxy.

I could not integrate with my XMRIG, I believe I have forgotten some simple detail.

To start my XMRIG-PROXY, I use
`./xmrig-proxy -o xmr-usa.dwarfpool.com:8005 -u 'Wallet' -p x -k`
That is, on standard port 3333.

`./xmrig -o 10.70.60.3:3333 -u 003 -p x -k`

But in the web interface, I add the host and port, and nothing happens. Can you help me?

**Comment by dunklesToast** [comment]
You need to activate the API. Here the extract from the XMRIG Wiki:

 ![Image](https://i.imgur.com/oonVNvF.jpg)
The Port of the pool does not matter when you use the Frontend!
