### ISSUE TITLE
Update rate too fast

### ISSUE THREAD

**Issue by zhuccc** [dunklesToast/XMRigFrontend#5]
How can I change update rate to Every 10 seconds Or longer.
This version on my pc is update to fast.
Maybe dozens of times per second.

**Comment by dunklesToast** [comment]
Hi!
In the index.js Line 43 change the 5000 to 10000. The refresh rate is in Milliseconds so you can easily change it to your 10 Seconds with 10000 (time*1000)

**Comment by dunklesToast** [comment]
Sorry. I meant Line 44.
(Can’t edit comments on mobile App)

**Comment by zhuccc** [comment]
Thank you.
I change the 5000 to 10000.
But nothing changed.
This is the Screenshots.
https://imgur.com/a/j86HE

**Comment by dunklesToast** [comment]
I assume you have reloaded the page and checked for Caching issues. Could you send a screenshot of the code?

**Comment by paulie-g** [comment]
@zhuccc You can try my fork or apply the diff from the pull request. Change '5000' in the code for whatever value you wish in milliseconds.

**Comment by zhuccc** [comment]
No matter how I modify the original program, the update frequency is the same fast.
And I use the fork and now work nice.
Thank you to your help.

**Comment by dunklesToast** [comment]
The "real mistake" was here:
`x = setTimeout(update(), 5000);` it needs to be `x = setTimeout(update, 5000);` (without the brackets after update). With the brackets the function is called instantly and not after 5 Seconds. Missed that - the PR fixed that for now but I will overwrite soon
